config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  root 'cocktails#index'
  resources :cocktails, only: [:index, :show, :new, :create] do 
    resources :doses, only: [:new, :create]
  end 
  delete 'doses/:id', to: 'doses#destroy', as: 'doses' 
end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_attachment :photo
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates_uniqueness_of :ingredient_id, scope: :cocktail_id
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [ :show ]
  def index
    @cocktails = Cocktail.all
    @cocktail = Cocktail.new
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
    @dose = @cocktail.doses.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      @cocktail.doses.create(dose_params)
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end


  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :picture, :photo)
  end

  def dose_params
    params.require(:cocktail).require(:dose).permit(:description, :ingredient_id)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = @cocktail.doses.new(dose_params)
    if @dose.save!
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = Cocktail.find(@dose.cocktail_id)
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end


  private
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for([ @cocktail ], html: { multipart: true }) do |f| %>
<%= f.input :name, label: 'Name your cocktail' %>

<%= f.simple_fields_for :dose do |form_dose| %>
<%= form_dose.input :description, label: 'Dose' %>
<%= form_dose.input :ingredient_id, label: "Ingredient", as: :select, collection: Ingredient.all %>
<% end %>

<%= f.button :submit %>
<% end %>

app/views/cocktails/index.html.erb
<div class="content">
  <div class="container">
    <div class="row">
      <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
        <div class="box">
          <% if cocktail.photo? %>
          <div class="box-icon" style="background-image: url('<%= cl_image_path cocktail.photo.path, width: 100, height: 100, crop: :fill%>');"></div>
          <% end %>
          <div class="info">
            <h4 class="text-center"><%=  cocktail.name %></h4>
            <%= link_to 'Read doses', cocktail_path(cocktail), class:"btn-treehouse" %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1>Let's create a new cocktail</h1>

<%= render 'form' %>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-lg-8 col-md-offset-2 ">
      <div class="box">
        <% if @cocktail.photo? %>
        <div class="">
          <div class="box-icon" style="background-image: url('<%= cl_image_path @cocktail.photo.path, width: 100, height: 100, crop: :fill%>');"></div>
          <% end %>
          <div class="info">
            <h4 class="text-center"><%= @cocktail.name %></h4>
            <% @cocktail.doses.each do |dose| %>
            <p>- <%= dose.ingredient.name %> : <%= dose.description %>
              <%= link_to doses_path(dose), method: :delete do  %>
              <i class="fa fa-trash"></i>
              <% end %></p>
              <% end %>
              <a  style="cursor:pointer" type="button" class="btn-treehouse" data-toggle="modal" data-target="#myModal">
                Add doses
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Add doses</h4>
          </div>
          <div class="modal-body">
            <%= simple_form_for([ @cocktail, @dose ]) do |f| %>
            <%= f.input :ingredient_id, prompt: "Ingredient", as: :select, collection: Ingredient.all %>
            <%= f.input :description, prompt: 'Procedure' %>
            <%= f.button :submit, class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

app/views/doses/_form.html.erb
<%= simple_form_for([ @cocktail, @dose ]) do |f| %>

  <%= f.input :ingredient_id, label: "Ingredient", as: :select, collection: Ingredient.all %>
  <%= f.input :description, label: 'Procedure' %>

  <%= f.button :submit %>
<% end %>

app/views/doses/new.html.erb
<h1>What's in <%= @cocktail.name %>?</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wagon Summer Drink</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>

<body>
  <%= render 'shared/navbar' %>
  <div class="filter"></div>
  <%= yield %>
  <%= javascript_include_tag 'application' %>
  <%= cloudinary_js_config %>
</body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <a class="btn-treehouse" data-toggle="modal" data-target="#myCocktailModal">
      Add Cocktail
    </a>
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myCocktailModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add Cocktail</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for([ Cocktail.new ], html: { multipart: true }) do |f| %>
        <%= f.input :name, label: 'Name your cocktail' %>
        <%= f.simple_fields_for :dose do |form_dose| %>
        <%= form_dose.input :description, label: 'Dose' %>
        <%= form_dose.input :ingredient_id, label: "Ingredient", as: :select, collection: Ingredient.all %>
        <%= f.input :photo, as: :attachinary %>
        <% end %>
        <%= f.button :submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>